sudo: false
dist: xenial

cache:
  apt: true
  ccache: true

git:
  depth: false

addons:
  apt:
    packages:
      - python3-pip
      - latexmk
      - libalgorithm-diff-perl
      - texlive
      - texlive-latex-extra
      - texlive-humanities
      - texlive-generic-recommended
      - graphviz
      - texlive-generic-extra
      - binutils-powerpc64-linux-gnu
      - gcc
      - g++
      - binutils


language: python
python:
  - "3.6"
install:
  - "pip3 install -r requirements.txt"
  - "pip3 install -r doc/requirements.txt"
  - ci/build-qemu-powernv.sh
  - ./bootstrap.sh
script:
  - ./ci/run-self-tests.sh
  - ./ci/run-qemu-tests.sh
#  - (cd doc/; make latexpdf html)

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  local_dir: "doc/_build/html"
  on:
    branch: master
